image: alpine

variables:
  SBT_VERSION: "1.2.8"
  SBT_OPTS: "-Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=2G -Xss2M  -Duser.timezone=GMT -Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: sbt-cache/coursier

stages:
  - test
  - integration
  - deploy

cache:
  key: "mycachekey"
  paths:
    - "sbt-cache/ivy/cache"
    - "sbt-cache/boot"
    - "sbt-cache/sbtboot"
    - "sbt-cache/target"
    - "sbt-cache/coursier"

test:
  tags:
    - cluster01
  stage: test
  image: "hseeberger/scala-sbt:8u181_2.12.8_1.2.8"
  script:
    - sbt clean coverageOn test coverageOff coverageReport coverageAggregate
  only:
    - /^develop$/
    - /(^feature\/.*)/
    - /(^hotfix\/.*)/
    - /(^release\/v([0-9]+)\.([0-9]+))/

integration:
  tags:
    - cluster01
  stage: integration
  image: "hseeberger/scala-sbt:8u181_2.12.8_1.2.8"
  script:
    - sbt clean it:test
  only:
    - /(^release\/v([0-9]+)\.([0-9]+))/

deploy:
  tags:
    - cluster01
  stage: deploy
  image: "hseeberger/scala-sbt:8u181_2.12.8_1.2.8"
  script:
    - sbt clean publish
